---

- name: Template local_settings.py
  template:
    src: local_settings.py.j2
    dest: "{{ horizon_config }}"
    owner: root
    group: root
    mode: 0644

- name: Ensure WSGIApplicationGroup is present
  lineinfile:
    path: /etc/apache2/conf-available/openstack-dashboard.conf
    line: "WSGIApplicationGroup %{GLOBAL}"
    insertafter: EOF

