---
- name: Install and configure Keystone
  hosts: controller
  become: true

  tasks:
    - name: Debug keystone_db_pass variable
      debug:
        var: keystone_db_pass

  roles:
    - keystone

