---
- name: Install and configure Keystone
  hosts: controller
  become: true

  vars:
    mysql_root_password: "dbpass"
    keystone_db_pass: "dbkeystone"
    keystone_admin_pass: "keystoneadmin"

  roles:
    - keystone

