- name: Create admin-openrc.sh file
  copy:
    dest: /root/admin-openrc.sh
    content: |
      export OS_PROJECT_DOMAIN_NAME=Default
      export OS_USER_DOMAIN_NAME=Default
      export OS_PROJECT_NAME=admin
      export OS_USERNAME=admin
      export OS_PASSWORD={{ keystone_admin_pass }}
      export OS_AUTH_URL=http://controller:5000/v3
      export OS_IDENTITY_API_VERSION=3
      export OS_IMAGE_API_VERSION=2
  owner: root
  group: root
  mode: '0600'
