---
- name: Create placement user
  openstack.cloud.identity_user:   # full module path
    auth: "{{ os_auth }}"
    name: placement
    password: "{{ placement_pass }}"
    default_project: service
    state: present

- name: Add admin role to placement user
  openstack.cloud.role_assignment:
    auth: "{{ os_auth }}"
    user: placement
    role: admin
    project: service
    state: present

- name: Create placement service
  openstack.cloud.catalog_service:
    auth: "{{ os_auth }}"
    name: placement
    type: placement
    description: "Placement API"
    state: present

- name: Create placement endpoints (public/internal/admin)
  openstack.cloud.endpoint:
    auth: "{{ os_auth }}"
    service: placement
    interface: "{{ item.interface }}"
    url: "http://{{ controller_hostname }}:8778"
    region: "{{ keystone_region }}"
    state: present
  loop:
    - { interface: 'public' }
    - { interface: 'internal' }
    - { interface: 'admin' }

