---

- name: Create placement user
  openstack.cloud.user:
    name: placement
    password: "{{ placement_pass }}"
    default_project: service
    state: present
    auth: "{{ os_auth }}"

- name: Add admin role to placement user
  openstack.cloud.user_role:
    user: placement
    role: admin
    project: service
    state: present
    auth: "{{ os_auth }}"

- name: Create placement service
  openstack.cloud.service:
    name: placement
    type: placement
    description: "Placement API"
    state: present
    auth: "{{ os_auth }}"

- name: Create placement endpoints (public/internal/admin)
  openstack.cloud.endpoint:
    service: placement
    interface: "{{ item.interface }}"
    url: "http://{{ controller_hostname }}:8778"
    region: "{{ keystone_region }}"
    state: present
    auth: "{{ os_auth }}"
  loop:
    - { interface: 'public' }
    - { interface: 'internal' }
    - { interface: 'admin' }

