---
- name: Configure neutron.conf
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf

- name: Configure ML2 plugin
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini

- name: Configure Open vSwitch agent
  template:
    src: openvswitch_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini

- name: Configure L3 agent
  template:
    src: l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
  when: neutron_network_option == 2 and 'controller' in group_names

- name: Configure DHCP agent
  template:
    src: dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini

