---
- name: Ensure ML2 plugin dir exists
  file:
    path: /etc/neutron/plugins/ml2
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure neutron.conf
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
  notify: restart neutron-server

- name: Configure ML2 plugin
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
  notify: restart neutron-server

- name: Configure Open vSwitch agent
  template:
    src: openvswitch_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
  notify: restart neutron-openvswitch-agent

- name: Configure L3 agent
  template:
    src: l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
  when: neutron_network_option == 2 and "'controller' in group_names"
  notify: restart neutron-l3-agent

- name: Configure DHCP agent
  template:
    src: dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini
  notify: restart neutron-dhcp-agent

