---
- name: Create Neutron user in Keystone
  openstack.cloud.user:
    cloud: default
    state: present
    name: "{{ neutron_user }}"
    password: "{{ neutron_pass }}"
    domain: default

- name: Assign admin role to Neutron user
  openstack.cloud.role:
    cloud: default
    name: admin
    user: "{{ neutron_user }}"
    project: service

- name: Create Neutron service
  openstack.cloud.service:
    cloud: default
    name: neutron
    type: network
    description: OpenStack Networking

- name: Create Neutron endpoints
  openstack.cloud.endpoint:
    cloud: default
    service: neutron
    interface: "{{ item.interface }}"
    url: "http://controller:9696"
    region: "{{ region_name }}"
  loop:
    - { interface: 'public' }
    - { interface: 'internal' }
    - { interface: 'admin' }

- name: Populate Neutron DB
  command: >
    su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf
    --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron

