---
- name: Ensure Python deps for Neutron DB and OpenStack CLI
  apt:
    name:
      - python3-pymysql
      - python3-openstackclient
    state: present
    update_cache: yes

# Controller node packages
- name: Install Neutron packages on controller
  apt:
    name: "{{ neutron_controller_packages }}"
    state: present
    update_cache: yes
  when: "'controller' in group_names"

# Compute node packages
- name: Install Neutron packages on compute
  apt:
    name: "{{ neutron_compute_packages }}"
    state: present
    update_cache: yes
  when: "'compute' in group_names"

