---
- name: Install Neutron packages
  apt:
    name:
      - neutron-server
      - neutron-plugin-ml2
      - neutron-openvswitch-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
      - "{{ 'neutron-l3-agent' if neutron_network_option == 2 and 'controller' in group_names else '' }}"
    state: present
    update_cache: yes

