---
- name: Install Neutron packages
  import_tasks: install.yml

- name: Optional OVS host setup (controller/compute)
  import_tasks: ovs_setup.yml
  when: manage_provider_bridge | bool

- name: Configure Neutron server
  import_tasks: configure.yml

- name: Create Neutron database
  import_tasks: db.yml

- name: Configure controller node
  import_tasks: controller.yml
  when: "'controller' in group_names"

- name: Configure compute node
  import_tasks: compute.yml
  when: "'compute' in group_names"

- name: Configure metadata agent
  import_tasks: metadata.yml

- name: Finalize (DB sync, restarts, optional provider network)
  import_tasks: finalize.yml

