---
- name: Template glance-api.conf
  template:
    src: glance-api.conf.j2
    dest: /etc/glance/glance-api.conf
    owner: root
    group: root
    mode: 0644

- name: Populate the glance DB
  command: glance-manage db_sync
  become_user: glance

- name: Restart Glance service
  service:
    name: glance-api
    state: restarted

